matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.8.1
  - os: osx
    language: generic
    env: PYTHON=3.7.6
  - os: osx
    language: generic
    env: PYTHON=3.6.10
  - os: linux
    language: python
    python: 2.7
    env: BUILDDOC=1

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi

install:
  - python -m pip install -U pip
  - python -m pip install setuptools
  - python -m pip install wheel numpy scipy matplotlib periodictable wxpython bumps sphinx nose
  - python setup.py bdist_wheel

script:
  - python --version
  - python setup.py test
  - python check_examples.py --chisq
  - if [ -n "$BUILDDOC" ]; then make html; fi

deploy:
  provider: releases
  prerelease: true
  skip-cleanup: true
  file_glob: true
  api_key:
    secure: jIGTuuAw9GwsIYwxIFL6qlYCS8aRGOsYlmEiOy9aYOkpZFJHkLW2eYIdqka4qdoxeUuyTRkiIkG71uCh/RRQNwFOEZXZcjQmK7lkFCr1COOSwFPfOYjGX1tdnRNpOwWRxJQpqIrEsbYrWHm0WilBSss8ONa4lC0uFA46u0KhGTY=
  file: dist/*
  on:
    tags: true
