name: Build webview with Jupyter

on:
  workflow_dispatch:

env:
  branch_name: webview

jobs:
  test_and_build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, py: 3.11 }
          - { os: windows-latest, py: "3.11" }
          - { os: macos-latest, py: "3.11" }
          - { os: macos-13, py: "3.11" }
          # all using to stable abi

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.branch_name }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.config.py }}
        shell: bash

    - name: Build webview packed
      shell: bash -el {0}
      run: |
        conda activate base
        ./extra/build_conda_packed_jupyter.sh
        ls artifacts
    - name: Update release assets and text
      uses: actions/github-script@v7
      env:
        SEARCH_PATTERN: "artifacts/*"
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const script = require('./.github/actions/update_unstable.js');
          const output = await script({github, context, glob});
          console.log(output);